/* Lightweight contract checks for the phone-editor/watch protocol. */
var fs = require('fs');
var assert = require('assert');
var pkjs = fs.readFileSync('src/pkjs/index.js', 'utf8');
var nativeCode = fs.readFileSync('src/c/main.c', 'utf8');
var config = fs.readFileSync('config/index.html', 'utf8');

assert(/sendNext\(index, attempt\)/.test(pkjs) && /180/.test(pkjs), 'phone should pace every saved field for the physical connection');
assert(/shouldSendTransport/.test(pkjs) && /transportTouched/.test(config), 'normal saves should preserve watch playback state');
assert(/&source=phone&notice=/.test(pkjs), 'Settings should open immediately from the saved phone copy');
assert(/defaultSettings/.test(pkjs), 'phone editor should start with the app defaults rather than blank patterns');
assert(/Save &amp; Close/.test(config), 'editor should offer one explicit close-to-save action');
assert(/PCM underrun/.test(nativeCode) && /voice \* 5 \/ 2/.test(nativeCode), 'audio should log real underruns and use per-voice drum gains');
assert(/MIX_BUFFER_SAMPLES 160/.test(nativeCode) && /MIX_PUMP_INTERVAL_MS 5/.test(nativeCode), 'audio should retain its proven full-quality stream block size');
assert(/timing-sensitive grid animation/.test(nativeCode) && !/s_playhead/.test(nativeCode), 'playback should use a simple static status indicator');
assert(/close_speaker_stream/.test(nativeCode) && /speaker_stream_close\(\)/.test(nativeCode), 'PCM streams should close on stop and teardown');
assert(/heap_bytes_free\(\)/.test(nativeCode) && /QUEUED NEXT BAR/.test(nativeCode), 'live-safe updates should use an adaptive standby cache');
assert(/persist_write_data\(PERSIST_SYNTH_NOTES_BLOB_BASE/.test(nativeCode), 'synth note edits should persist as one compact track blob');
assert(/MESSAGE_KEY_Volume/.test(nativeCode) && /MESSAGE_KEY_Drive/.test(nativeCode) && /MESSAGE_KEY_Space/.test(nativeCode), 'watch should accept all three effect controls');
assert(/id="volume"/.test(config) && /id="drive"/.test(config) && /id="space"/.test(config), 'editor should expose the three effect sliders');
assert(/MESSAGE_KEY_BassAttack/.test(nativeCode) && /MESSAGE_KEY_LeadDecay/.test(nativeCode), 'watch should accept per-synth envelope controls');
assert(/stored_bass_attack/.test(nativeCode) && /stored_bass_decay/.test(nativeCode) && /stored_lead_attack/.test(nativeCode) && /stored_lead_decay/.test(nativeCode), 'persisted synth envelope controls should load after relaunch');
assert(/MESSAGE_KEY_DriveTargets/.test(nativeCode) && /MESSAGE_KEY_SpaceTargets/.test(nativeCode), 'watch should accept Drive and Space routing');
assert(/id="bass-cutoff"/.test(config) && /id="lead-bite"/.test(config), 'editor should expose synth-shape sliders');
assert(/drive-targets/.test(config) && /space-targets/.test(config), 'editor should expose effect routing checkboxes');
assert(!/RequestSettings/.test(nativeCode), 'obsolete watch-to-phone settings request should be removed');
assert(!/settingsRequestPart/.test(pkjs), 'opening Settings should not wait for a second state round-trip');
assert(/cachedState/.test(config) && /disabled = true/.test(config), 'cached editor must be view-only');
assert(/Four on the floor/.test(config) && /Clear all notes/.test(config), 'editor should offer presets and clearing');
assert(/track-section/.test(config) && /press and hold/i.test(fs.readFileSync('README.md', 'utf8')), 'editor should keep tracks compact and document pitch decrement');
assert(config.indexOf('innerHTML') === -1, 'editor should use textContent for text updates');
console.log('Phone/editor protocol checks passed.');
